import type { Review } from "@/app/types/review";

/**
 * Seed data. Hand-crafted to give the dashboard's filter, sort, summary,
 * and empty-state stories real shape — mixed statuses, mixed ratings,
 * obviously concerning content (bedbugs, hair in bathroom, mislabeled
 * non-smoking) so the "pending + low rating" surface story has something
 * to show. Used by `scripts/setup-db.ts` to populate an empty database.
 */
export const seedReviews: Review[] = [
  {
    id: 1001,
    guestName: "Maria Santos",
    guestAvatar: "https://i.pravatar.cc/80?u=maria",
    propertyName: "Canal View Apartment",
    city: "Amsterdam",
    channelSource: "airbnb",
    rating: 4,
    text: "Beautiful apartment with great views. The check-in process was smooth. Only minor issue was the wifi being slow in the evenings.",
    status: "pending",
    createdAt: "2026-05-10T14:30:00Z",
    response: null,
  },
  {
    id: 1002,
    guestName: "James Chen",
    guestAvatar: "https://i.pravatar.cc/80?u=james",
    propertyName: "Kreuzberg Loft",
    city: "Berlin",
    channelSource: "booking.com",
    rating: 2,
    text: "The location was fine but the apartment was not clean on arrival. Had to wait 2 hours for someone to come re-clean. Very disappointing.",
    status: "pending",
    createdAt: "2026-05-09T09:15:00Z",
    response: null,
  },
  {
    id: 1003,
    guestName: "Sophie Dubois",
    guestAvatar: "https://i.pravatar.cc/80?u=sophie",
    propertyName: "Marais Studio 4B",
    city: "Paris",
    channelSource: "direct",
    rating: 5,
    text: "Perfect stay! Everything was exactly as described. Will definitely book again.",
    status: "approved",
    createdAt: "2026-05-08T18:45:00Z",
    response: "Thank you Sophie! We look forward to hosting you again.",
  },
  {
    id: 1004,
    guestName: "Oliver Müller",
    guestAvatar: "https://i.pravatar.cc/80?u=oliver",
    propertyName: "Kreuzberg Loft",
    city: "Berlin",
    channelSource: "airbnb",
    rating: 1,
    text: "Hair in the bathroom, stained sheets, broken shower. We left after one night and are requesting a refund. Avoid.",
    status: "pending",
    createdAt: "2026-05-12T08:00:00Z",
    response: null,
  },
  {
    id: 1005,
    guestName: "Aiko Tanaka",
    guestAvatar: "https://i.pravatar.cc/80?u=aiko",
    propertyName: "Shoreditch Studio",
    city: "London",
    channelSource: "direct",
    rating: 5,
    text: "Lovely host, great communication, immaculate space. The neighborhood guide they sent ahead was a thoughtful touch.",
    status: "approved",
    createdAt: "2026-05-07T20:10:00Z",
    response: null,
  },
  {
    id: 1006,
    guestName: "Carlos Vega",
    guestAvatar: "https://i.pravatar.cc/80?u=carlos",
    propertyName: "Gracia Terrace",
    city: "Barcelona",
    channelSource: "booking.com",
    rating: 3,
    text: "Apartment was as described but the air conditioning was loud and we couldn't get it to turn off at night. Slept poorly.",
    status: "pending",
    createdAt: "2026-05-11T11:45:00Z",
    response: null,
  },
  {
    id: 1007,
    guestName: "Emma Larsson",
    guestAvatar: "https://i.pravatar.cc/80?u=emma",
    propertyName: "Marais Studio 4B",
    city: "Paris",
    channelSource: "airbnb",
    rating: 4,
    text: "Cozy studio in a perfect location. Stairs were a workout but worth it for the view.",
    status: "approved",
    createdAt: "2026-05-06T16:20:00Z",
    response: null,
  },
  {
    id: 1008,
    guestName: "Rahul Mehta",
    guestAvatar: "https://i.pravatar.cc/80?u=rahul",
    propertyName: "Canal View Apartment",
    city: "Amsterdam",
    channelSource: "direct",
    rating: 2,
    text: "Listing photos are misleading. The 'canal view' is partially blocked by construction scaffolding. Should be disclosed.",
    status: "flagged",
    createdAt: "2026-05-09T13:00:00Z",
    response: null,
  },
  {
    id: 1009,
    guestName: "Nora Haugen",
    guestAvatar: "https://i.pravatar.cc/80?u=nora",
    propertyName: "Shoreditch Studio",
    city: "London",
    channelSource: "airbnb",
    rating: 5,
    text: "Best stay I've had in London. Quiet, clean, fast wifi, and the bed was incredibly comfortable.",
    status: "pending",
    createdAt: "2026-05-12T19:30:00Z",
    response: null,
  },
  {
    id: 1010,
    guestName: "Felix Brandt",
    guestAvatar: "https://i.pravatar.cc/80?u=felix",
    propertyName: "Kreuzberg Loft",
    city: "Berlin",
    channelSource: "booking.com",
    rating: 4,
    text: "Solid place. Kitchen well-stocked. Only knock is the street noise on weekends.",
    status: "approved",
    createdAt: "2026-05-05T10:00:00Z",
    response: null,
  },
  {
    id: 1011,
    guestName: "Priya Shah",
    guestAvatar: "https://i.pravatar.cc/80?u=priya",
    propertyName: "Gracia Terrace",
    city: "Barcelona",
    channelSource: "airbnb",
    rating: 5,
    text: "Terrace was the highlight. Watched the sunset every evening. Will rebook.",
    status: "approved",
    createdAt: "2026-05-04T21:00:00Z",
    response: "So glad you enjoyed the terrace, Priya!",
  },
  {
    id: 1012,
    guestName: "Diego Romero",
    guestAvatar: "https://i.pravatar.cc/80?u=diego",
    propertyName: "Marais Studio 4B",
    city: "Paris",
    channelSource: "booking.com",
    rating: 1,
    text: "Bed bugs. Reported to host, no response for 6 hours. Had to find another place at 11pm. Will be disputing the charge.",
    status: "pending",
    createdAt: "2026-05-13T07:00:00Z",
    response: null,
  },
  {
    id: 1013,
    guestName: "Hannah Park",
    guestAvatar: "https://i.pravatar.cc/80?u=hannah",
    propertyName: "Shoreditch Studio",
    city: "London",
    channelSource: "direct",
    rating: 3,
    text: "Fine for the price. Heating took ages to warm up the room, but otherwise no complaints.",
    status: "pending",
    createdAt: "2026-05-10T22:15:00Z",
    response: null,
  },
  {
    id: 1014,
    guestName: "Tomás Lehmann",
    guestAvatar: "https://i.pravatar.cc/80?u=tomas",
    propertyName: "Canal View Apartment",
    city: "Amsterdam",
    channelSource: "airbnb",
    rating: 5,
    text: "Effortless from booking to check-out. The welcome basket was a sweet touch.",
    status: "approved",
    createdAt: "2026-05-03T14:00:00Z",
    response: null,
  },
  {
    id: 1015,
    guestName: "Yuki Sato",
    guestAvatar: "https://i.pravatar.cc/80?u=yuki",
    propertyName: "Gracia Terrace",
    city: "Barcelona",
    channelSource: "direct",
    rating: 2,
    text: "Smelled strongly of cigarette smoke despite the non-smoking listing. Could not air it out enough to sleep comfortably.",
    status: "flagged",
    createdAt: "2026-05-11T17:30:00Z",
    response: null,
  },
];
